### ISSUE TITLE
HomeView 리프레시 스크롤시 화면 내려가는 문제

### ISSUE THREAD

**Issue by yangsubinn** [dnd-side-project/dnd-9th-2-ios#106]
## 📌 요약

https://github.com/dnd-side-project/dnd-9th-2-ios/assets/81167570/a2ef03da-d13c-4f40-ad1b-dde80028e0f6

## 📋 내용

- 화면이 내려가요

**Comment by never-better** [comment]
😱 🫠 🫥

**Comment by yangsubinn** [comment]
보니까 프리뷰에서는 저렇게 내려오는데 실기기에서는 안그런 것 같기도 하네요 ..? 일단 지켜보겠습니다 .. 🧐

**Comment by never-better** [comment]
프리뷰는 버그 많아서 실기기에서만 안 나타나면 괜찮을 것 같습니다.
