### ISSUE TITLE
회원가입, 로그인 이후 마이페이지 유저 정보 반영 X

### ISSUE THREAD

**Issue by yangsubinn** [dnd-side-project/dnd-9th-2-ios#163]
## 📌 요약
회원가입, 로그인 이후 마이페이지 유저 정보 반영 X

## 📋 내용

-

**Comment by never-better** [comment]
아예 반영이 안되는 건가요 아니면 회원가입, 로그인하고 앱 종료하고 다시 키면 반영이 되는 건가요??

**Comment by yangsubinn** [comment]
바로 로그아웃하고 로그인한 경우 반영이 안되고, 앱을 나갔다가 들어오면 반영되어있습니다
https://github.com/dnd-side-project/dnd-9th-2-ios/assets/81167570/6d5a4b33-9014-4fc6-8753-5deda1522ef0

**Comment by never-better** [comment]
오잉 영상에서는 잘 작동하는데 아닌가요??

**Comment by yangsubinn** [comment]
> 바로 로그아웃하고 로그인한 경우 반영이 안되고, 앱을 나갔다가 들어오면 반영되어있습니다 https://github.com/dnd-side-project/dnd-9th-2-ios/assets/81167570/6d5a4b33-9014-4fc6-8753-5deda1522ef0

'카카오 로그인 상태 -> 로그아웃 -> 애플 로그인 -> 마이페이지에 애플 로그인 정보 노출' 요 상태입니다!
이전 로그인했던 정보가 보여지거나, 로그인한 적이 없는 경우 에러 프로필이 보여집니다

**Comment by never-better** [comment]
아 애플로그인을 한 거였네요. 확인했습니다.
