### ISSUE TITLE
한국 시간대 고정

### ISSUE THREAD

**Issue by yangsubinn** [dnd-side-project/dnd-9th-2-ios#168]
## 📌 요약
- Date() 한국 시간대 / 그리니치 시간대 복합적으로 사용되는 문제 해결

## 📋 내용

- 한국 시간대 고정

**Comment by yangsubinn** [comment]
혹시 모임 생성 부분에서 시간 제대로 반영되나요? @never-better 
<img src="https://github.com/dnd-side-project/dnd-9th-2-ios/assets/81167570/57d9db3e-d59a-4719-b553-ac20d3f50d0d" width=300 >

**Comment by never-better** [comment]
모임 생성 시간이 제대로 반영된다는 게 어떤건가요??

우선 View에 나온 시간이랑 응답으로 온 모임 시간은 동일합니다.

**Comment by yangsubinn** [comment]
모임 생성 과정에서 시간 부분에 보여지는 것과 datePicker에서 보여지는 시간, 모임 생성 완료 뷰에서 보여지는 시간이 다릅니다
저만 이런건가 해서 여쭤봤는데, 
서버 요청 자체는 의도한 시간대로 들어가는 것을 보니, 날짜-시간 데이터를 뷰에 보이는 과정에서 한국시간대가 적용되지 않고 그리니치 시간대로 변환되어 보여지는 것 같습니다

의도와 다르게 나오는 날짜
- CreateDateView의 Form
- CreateSuccessView의 날짜

의도대로 나오는 날짜
- CreateDateView에서 DatePicker
- HomeView의 리스트 상 날짜

모임 생성 과정 녹화 (시간 부분 주의)
- 녹화 당시 시각 12:24
- datepicker에 뜨는 시각 + CreateDateView에 보여져야 하는 시각 14:30
- CreateDateView에 보여지는 시각 5:30 

https://github.com/dnd-side-project/dnd-9th-2-ios/assets/81167570/5744b4d2-39b8-47f0-a5ba-84eee1880cc7

| 생성 완료 뷰 | 생성 완료 후 홈 |
|--|--|
|![IMG_F9A567ACA6CE-1](https://github.com/dnd-side-project/dnd-9th-2-ios/assets/81167570/2e7c4a88-cfde-490b-8e11-9fa3bbc79d27) | ![IMG_6448C3D1A9E6-1](https://github.com/dnd-side-project/dnd-9th-2-ios/assets/81167570/802aef27-d3a4-4f70-a3da-42c15abbd4c6) |

**Comment by never-better** [comment]
저는 아래 그림 같이 나오고 있어요.

제 환경은
- Xcode 14.3
- 시뮬레이터 iOS 164.
- 시뮬레이터 - 설정 - 일반 - 언어 및 지역 - 한국어
이렇게입니다.

<img width = 300 src = "https://github.com/dnd-side-project/dnd-9th-2-ios/assets/71776532/bd163f0e-0e28-4e75-9dd3-5de5ea01faf8" />

<img width = 300 src = "https://github.com/dnd-side-project/dnd-9th-2-ios/assets/71776532/beb26d72-5890-4410-8ef9-333d34499c50" />


혹시 핸드폰에 설치해서 해도 똑같은지 확인 가능할까요??

**Comment by yangsubinn** [comment]
위에 스크린샷이랑 영상 모두 실기기에서 돌린 결과입니다 !
